mesh:
  udp:
    group1:
      - 172.26.190.212 # terra
      - 172.26.190.142 # mare
  tcp:
    group2:
      - 172.26.190.212 # terra
      - 172.26.190.142 # mare
  roce:
    group3:
      - 0.0.0.0 # dummy
  ib:
    group4:
      - 0.0.0.0 # dummy

arrow:
  tcp:
    group5:
      src:
        - 172.26.190.212 # terra
      dst:
        - 172.26.190.212 # terra
        - 172.26.190.142 # mare

  